 services:
    smart-home:
        image: barbaris/smart-home:alpha-1
        container_name: smart-home
        network_mode: host
        volumes:
            - ./smart-home-data/logs:/app/logs
            - ./smart-home-data/config:/app/config
