### LOG IN
POST https://auth.barbaris.in/login
Content-Type: application/json

{
  "username": "{{google_home_username}}",
  "password": "{{google_home_password}}",
  "client_id": "{{google_home_client_id}}"
}

> {%
    client.test('Request executed successfully', function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test('Response contains code', function () {
        client.assert(response.body.code !== undefined, "Code is undefined");
    });

    const {code} = response.body;
    client.global.set("code", code);
%}

### Get refresh token by code
POST https://auth.barbaris.in/token
Content-Type: application/json

{
  "grant_type": "authorization_code",
  "code": "{{code}}"
}

> {%
    client.test('Request executed successfully', function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test('Response contains refresh token', function () {
        client.assert(response.body.refresh_token !== undefined, "Refresh token is undefined");
    });

    client.test('Response contains access token', function () {
        client.assert(response.body.access_token !== undefined, "Access token is undefined");
    });

    const {refresh_token, access_token} = response.body;
    client.global.set("refresh_token", refresh_token);
    client.global.set("access_token", access_token);
%}

### Test
GET {{base_uri}}/

### SYNC
POST {{base_uri}}/fulfillment/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "requestId": "Hello SYNC!",
  "inputs": [
    {
      "intent": "action.devices.SYNC"
    }
  ]
}

### QUERY
POST {{base_uri}}/fulfillment/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "requestId": "Hello QUERY!",
    "inputs": [
      {
        "intent": "action.devices.QUERY",
        "payload": {
          "devices": [
            {
            "id": "0x00158d0002b7d6be"
          },
          {
              "id": "0x00158d0004112e6f"
            },
            {
            "id": "0x00158d000446a373"
          },
          {
              "id": "0x00158d00041138dd"
            },
            {
              "id": "0x00158d0004112e41"
            }
          ]
        }
      }
  ]
  }

### EXECUTE
POST {{base_uri}}/fulfillment/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "requestId": "Hello EXECUTE!",
  "inputs": [
    {
      "context": {
        "locale_country": "US",
        "locale_language": "en"
      },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "devices": [
              {
                "id": "0x00158d00041138dd"
              }
            ],
            "execution": [
              {
                "command": "action.devices.commands.ColorAbsolute",
                "params": {
                  "color": {
                    "temperature": 6000
                  }
                }
              }
            ]
          }
        ]
      }
    }
  ]
}
